# Migration configuration
sql:
  migration:
    configuration: import.xml
  batchsize: 10
  result:
    limit: 200
    offset: 0
mongodb:
  timeout:
    connection: 10000
    read: 10000
# Datasource configuration
spring:
  datasource:
    driver-class-name: 
    password: 
    username: 
    url: 
  data:
    mongodb: 
      database: 
      grid-fs-database: 
      uri: 
      repositories:
        enabled: true
